menu:
    Blog: /
    Archive: /archives/
    #Tags: todo
    #Weibo: 
    GitHub: https://github.com/Raumss
    #Rss: /atom.xml

favicon: /uploads/global/favicon.png
logo: /uploads/global/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
